# Site settings
title: Vaskar Dahal
description: This is a page about Vaskar Dahal & his projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SereneWizard
user_description: An enthusiastic, team-oriented and adaptive individual with a research experience in the interdisciplinary trifecta of climate-water-agriculture. I have worked towards developing an understanding of the agricultural processes and its climatic determinants by combining the strengths of spatial knowledge, data science and physical modeling. I am highly motivated towards using programming, quantitative approaches, statistics and spatial analysis for developing novel modelling solutions for solving problems.
user_title: Water Resources Engineer, Geospatial Analylst
email: anon@anon.com
twitter_username: serene_wizard
github_username:  SereneWizard
gplus_username:  lorem_ipsum

# My collections
collections:
  my_collections:
    output: true

# Google-analytics
google-analytics:
  id: ""




exclude: ['package.json', 'src' , 'node_modules']
